name: MERN Ecommerce CD

# Run after CI workflow completes
on:
  workflow_run:
    workflows:
      - MERN Ecommerce CI
    types:
      - completed

jobs:

  update-manifests:

    # Run only if CI was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    # Allow GitHub Actions to push changes
    permissions:
      contents: write

    steps:

      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: main

      # Get the image tag from CI commit
      - name: Set Image Tag
        run: |
          echo "IMAGE_TAG=$(echo ${{ github.event.workflow_run.head_sha }} | cut -c1-7)" >> $GITHUB_ENV

      # Update backend image tag
      - name: Update Backend Image
        run: |
          sed -i \
          "s|aliahmadsah/mern-ecommerce-backend:.*|aliahmadsah/mern-ecommerce-backend:${IMAGE_TAG}|g" \
          k8s/backend-deployment.yml

      # Update frontend image tag
      - name: Update Frontend Image
        run: |
          sed -i \
          "s|aliahmadsah/mern-ecommerce-frontend:.*|aliahmadsah/mern-ecommerce-frontend:${IMAGE_TAG}|g" \
          k8s/frontend-deployment.yml

      # Show manifest changes
      - name: Check Changes
        run: |
          git diff -- k8s/

      # Configure Git
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # Commit changes
      - name: Commit Changes
        run: |
          git add k8s/
          git commit -m "Update Kubernetes image tags"

      # Push changes to GitHub
      - name: Push Changes
        run: |
          git push origin main
