name: MERN Ecommerce CD

# Run after CI workflow completes
on:
  workflow_run:
    workflows:
      - MERN Ecommerce CI
    types:
      - completed

jobs:

  update-manifests:

    # Run only when CI succeeds
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    # Allow GitHub Actions to push changes
    permissions:
      contents: write

    steps:

      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: main

      # Update backend image tag
      - name: Update Backend Image
        run: |
          sed -i \
          "s|aliahmadshah/mern-ecommerce-backend:.*|aliahmadshah/mern-ecommerce-backend:${BACKEND_DOCKER_TAG}|g" \
          k8s/backend-deployment.yml

      # Update frontend image tag
      - name: Update Frontend Image
        run: |
          sed -i \
          "s|aliahmadshah/mern-ecommerce-frontend:.*|aliahmadshah/mern-ecommerce-frontend:${FRONTEND_DOCKER_TAG}|g" \
          k8s/frontend-deployment.yml

      # Check manifest changes
      - name: Check Changes
        run: |
          git diff -- k8s/

      # Configure Git
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # Commit manifest changes
      - name: Commit Changes
        run: |
          git add k8s/
          git commit -m "Update Kubernetes image tags"

      # Push changes to GitHub
      - name: Push Changes
        run: |
          git push origin main
